version: "3.7"

services:
  keycloak:
    build: .
    image: djeikyb/keycloak:3.0.0.Final
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:9.6.3
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=password
    ports:
      - "5432:5432"
